import pandas as pd
import pprint

df_players = pd.read_json("./output/players.json")
df_players = df_players[["id", "playerCode"]]
df_teams = pd.read_json("./output/teams.json")
df_player_totals = pd.read_pickle("./output/player-totals.pkl")
df_player_totals.index = df_player_totals.index.rename('id')

df_player_totals["ASSIST_PER_CHANCE"] = df_player_totals["ASSIST"] / \
    df_player_totals["ASSIST_CHANCE"]

df_player_totals["ASSIST_RATING"] = round((df_player_totals["ASSIST_PER_CHANCE"]-df_player_totals["ASSIST_PER_CHANCE"].min()) /
                                          (df_player_totals["ASSIST_PER_CHANCE"].max()-df_player_totals["ASSIST_PER_CHANCE"].min()) * 100)

# normalized_df = round((df_player_totals-df_player_totals.min()) /
#                       (df_player_totals.max()-df_player_totals.min()) * 100)

df = df_player_totals.merge(df_players, on="id", how="left")

print("End of file")


# print(df.describe())
# df_25 = df.describe(include='all').loc['25%']
# min_assist_chance = df_25["ASSIST_CHANCE"]
# df = df[df["ASSIST_CHANCE"] < df_25["ASSIST_CHANCE"]]
# df["ASSIST_PER_CHANCE"] = df["ASSIST"] / df["ASSIST_CHANCE"]


# df_max_scaled = df.copy()
# for column in df_max_scaled.columns:
#     df_max_scaled[column] = df_max_scaled[column] / \
#         df_max_scaled[column].abs().max()

# display(df_max_scaled)


# def normalize_data(min, max, value):
#     return round(((value - min) / (max - min)))


# ASSIST
# ASSIST_CHANCE
# BLOCK
# BLOCK_CHANCE
# FG_ARC_3_ATTEMPT
# FG_ARC_3_BLOCK
# FG_ARC_3_CHANCE_OFFENSIVE
# FG_ARC_3_CHANCE_DEFENSIVE
# FG_ARC_3_MADE
# FG_ARC_3_MADE_FOUL
# FG_AT_RIM_ATTEMPT
# FG_AT_RIM_BLOCK
# FG_AT_RIM_CHANCE_OFFENSIVE
# FG_AT_RIM_CHANCE_DEFENSIVE
# FG_AT_RIM_MADE
# FG_AT_RIM_MADE_FOUL
# FG_CORNER_3_ATTEMPT
# FG_CORNER_3_BLOCK
# FG_CORNER_3_CHANCE_OFFENSIVE
# FG_CORNER_3_CHANCE_DEFENSIVE
# FG_CORNER_3_MADE
# FG_CORNER_3_MADE_FOUL
# FG_LONG_MID_RANGE_ATTEMPT
# FG_LONG_MID_RANGE_BLOCK
# FG_LONG_MID_RANGE_CHANCE_OFFENSIVE
# FG_LONG_MID_RANGE_CHANCE_DEFENSIVE
# FG_LONG_MID_RANGE_MADE
# FG_LONG_MID_RANGE_MADE_FOUL
# FG_SHORT_MID_RANGE_ATTEMPT
# FG_SHORT_MID_RANGE_BLOCK
# FG_SHORT_MID_RANGE_CHANCE_OFFENSIVE
# FG_SHORT_MID_RANGE_CHANCE_DEFENSIVE
# FG_SHORT_MID_RANGE_MADE
# FG_SHORT_MID_RANGE_MADE_FOUL
# FG_TOTAL_ATTEMPT
# FG_TOTAL_BLOCK
# FG_TOTAL_CHANCE_OFFENSIVE
# FG_TOTAL_CHANCE_DEFENSIVE
# FG_TOTAL_MADE
# FG_TOTAL_MADE_FOUL
# FG_TOTAL_MISS_FOUL_2
# FG_TOTAL_MISS_FOUL_3
# FG_XY
# FOUL
# FOUL_CHANCE
# FOUL_AWAY_FROM_PLAY
# FOUL_AWAY_FROM_PLAY_CHANCE
# FOULED_AWAY_FROM_PLAY
# FOULED_AWAY_FROM_PLAY_CHANCE
# FOUL_CLEAR_PATH
# FOUL_CLEAR_PATH_CHANCE
# FOULED_CLEAR_PATH
# FOULED_CLEAR_PATH_CHANCE
# FOUL_COUNT_AS_PERSONAL
# FOUL_COUNT_AS_PERSONAL_CHANCE
# FOULED_COUNT_AS_PERSONAL
# FOULED_COUNT_AS_PERSONAL_CHANCE
# FOUL_COUNT_TOWARD_PENALTY
# FOUL_COUNT_TOWARD_PENALTY_CHANCE
# FOULED_COUNT_TOWARD_PENALTY
# FOULED_COUNT_TOWARD_PENALTY_CHANCE
# FOUL_DEFENSIVE_NON_SHOOTING
# FOUL_DEFENSIVE_NON_SHOOTING_CHANCE
# FOULED_DEFENSIVE_NON_SHOOTING
# FOULED_DEFENSIVE_NON_SHOOTING_CHANCE
# FOUL_DOUBLE
# FOUL_DOUBLE_CHANCE
# FOUL_FLAGRANT
# FOUL_FLAGRANT_CHANCE
# FOULED_FLAGRANT
# FOULED_FLAGRANT_CHANCE
# FOUL_FLAGRANT_1
# FOUL_FLAGRANT_1_CHANCE
# FOULED_FLAGRANT_1
# FOULED_FLAGRANT_1_CHANCE
# FOUL_FLAGRANT_2
# FOUL_FLAGRANT_2_CHANCE
# FOULED_FLAGRANT_2
# FOULED_FLAGRANT_2_CHANCE
# FOUL_INBOUND
# FOUL_INBOUND_CHANCE
# FOULED_INBOUND
# FOULED_INBOUND_CHANCE
# FOUL_LOOSE_BALL
# FOUL_LOOSE_BALL_CHANCE
# FOULED_LOOSE_BALL
# FOULED_LOOSE_BALL_CHANCE
# FOUL_OFFENSIVE_CHARGE
# FOUL_OFFENSIVE_CHARGE_CHANCE
# FOULED_OFFENSIVE_CHARGE
# FOULED_OFFENSIVE_CHARGE_CHANCE
# FOUL_OFFENSIVE_OTHER
# FOUL_OFFENSIVE_OTHER_CHANCE
# FOULED_OFFENSIVE_OTHER
# FOULED_OFFENSIVE_OTHER_CHANCE
# FOUL_OFFENSIVE_TOTAL
# FOUL_OFFENSIVE_TOTAL_CHANCE
# FOULED_OFFENSIVE_TOTAL
# FOULED_OFFENSIVE_TOTAL_CHANCE
# FOUL_PERSONAL
# FOUL_PERSONAL_CHANCE
# FOULED_PERSONAL
# FOULED_PERSONAL_CHANCE
# FOUL_PERSONAL_BLOCK
# FOUL_PERSONAL_BLOCK_CHANCE
# FOULED_PERSONAL_BLOCK
# FOULED_PERSONAL_BLOCK_CHANCE
# FOUL_PERSONAL_TAKE
# FOUL_PERSONAL_TAKE_CHANCE
# FOULED_PERSONAL_TAKE
# FOULED_PERSONAL_TAKE_CHANCE
# FOUL_SHOOTING
# FOUL_SHOOTING_CHANCE
# FOULED_SHOOTING
# FOULED_SHOOTING_CHANCE
# FOUL_SHOOTING_BLOCK
# FOUL_SHOOTING_BLOCK_CHANCE
# FOULED_SHOOTING_BLOCK
# FOULED_SHOOTING_BLOCK_CHANCE
# FOUL_TECHNICAL
# FOUL_TECHNICAL_CHANCE
# FOUL_TECHNICAL_DOUBLE
# FOUL_TECHNICAL_DOUBLE_CHANCE
# FT_ATTEMPT
# FT_MADE
# GAMES
# REBOUND_DEFENSIVE
# REBOUND_DEFENSIVE_CHANCE
# REBOUND_OFFENSIVE
# REBOUND_OFFENSIVE_CHANCE
# STEAL
# STEAL_CHANCE
# TURNOVER
# TURNOVER_CHANCE
# VIOLATION_DEFENSIVE_GOALTENDING
# VIOLATION_DEFENSIVE_GOALTENDING_CHANCE
# VIOLATION_DEFENSIVE_KICK_BALL
# VIOLATION_DEFENSIVE_KICK_BALL_CHANCE
